# Generated by Django 3.1.3 on 2025-01-06

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),  # Fixed import
        ),
    ]
